### ISSUE TITLE
Notification options not working

### ISSUE THREAD

**Issue by thiagomajesk** [dominique-mueller/notification-js#1]
Hi! 

Just started using your plugin but I just can't figure how to make this work: 

``` javascript
notification.notify("success", "My notification message", {position: [ "right", "top" ]})
```

Why my notification messages keep using the default configuration (position: [ "left", "botton" ])?

I've tested other options and it doesn't seem to work as well

**Comment by itsdevdom** [comment]
A notification configuration is generally split into different sections: `notification`, `symbol`, `message`, `dismiss`, `behaviour`, `animations` and `callbacks`.

Every option you define belongs to one of these sections. So the `position` option should be set within the `notification` section.

In your case the right command would be:

``` js
notification.notify("success", "My notification message", {
    notification: {
        position: [ "right", "top" ]
    }
});
```

You can take a look at the [example configuration](https://github.com/dominique-mueller/notification-js#default-global-options), there you can see the `position` option in the `notification` part.

Please let me know if that works fine.

**Comment by thiagomajesk** [comment]
I see... I think this should be highlighted with some example in the options section, though.That was not clear right away for me. Thanks! :smile: :+1:

**Comment by itsdevdom** [comment]
No problem :smile: 
I will update the docs soon to make this clearer for developers.
